name: build adocs

on:
  push:
    branches:
      - main
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: generate schema docs
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import environment variables
        id: import-env
        shell: bash
        run: cat .env >> $GITHUB_ENV

      - name: Build docs
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "./generate_schema_docs.sh -v ${{ env.SCHEMA_VERSION }}"

      - name: Copy src files
        shell: bash
        run: sudo cp src/*.csv dist/

      - name: Build index page
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: cd ./.github && sudo ./generate_index.sh -r "$GITHUB_REPOSITORY"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}